title: "US LAYER"
email: contact@uslayer.com
formspree: mjvj--------
timezone: UTC
baseurl: "/"
permalink: "/:title/"
logo: 'assets/images/logo.jpg'
favicon: 'assets/images/favicon.ico'
author: Admin
paginate: 30
disqus: 'uslayer'
locale: en_us
lang: en_us
feed_items: 10
feed_update_period: daily
feed_update_frequency: 1
markdown: kramdown
kramdown:
  syntax_highlighter_opts:
    disable: true
sass:
  sass_dir: _sass
  style: :compressed
ganalytics: UA-11111
fbpageid: xxxxx


# Social
social:
#  instagram: https://www.instagram.com/uslayer/
  facebook: https://www.facebook.com/uslayer
  twitter: https://twitter.com/us_layer
  youtube: https://www.youtube.com/uslayer

# Plugins
plugins:
- jekyll-paginate
- jekyll-sitemap
- jekyll-feed
- jekyll-seo-tag
- jekyll-archives
